### ISSUE TITLE
Installation of Google Tag Manager

### ISSUE THREAD

**Issue by AbichandaniKaneeka** [mikulaskafka/the-chocolate-shop-kaneeka#1]
Hi Mikulas, 

Please paste the below mentioned code onto every page of your website.

Note: Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PN8DFN6G');</script>

**Comment by AbichandaniKaneeka** [comment]
Also, paste this code immediately after the opening <body> tag


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PN8DFN6G"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


Please confirm once done, so that I can test the website at my end. 

Thanks for your help.

**Comment by AbichandaniKaneeka** [comment]
Website Link for your reference: https://mikulaskafka.github.io/the-chocolate-shop-kaneeka/

**Comment by mikulaskafka** [comment]
The code was added as instructed:

1. As high as possible on every page of the website:
`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-PN8DFN6G');</script>`

2. Immediately after the opening tag:
`<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PN8DFN6G" height="0" width="0" style="display:none;visibility:hidden"></iframe>`

Affected pages:
[/reviews](https://github.com/mikulaskafka/the-chocolate-shop-kaneeka/blob/e6d9bacd09f2695de85db3bd47f4a768a7644cae/reviews.html)
[/about](https://github.com/mikulaskafka/the-chocolate-shop-kaneeka/blob/main/about.html)
[/index](https://github.com/mikulaskafka/the-chocolate-shop-kaneeka/blob/e6d9bacd09f2695de85db3bd47f4a768a7644cae/index.html)
[/products](https://github.com/mikulaskafka/the-chocolate-shop-kaneeka/blob/e6d9bacd09f2695de85db3bd47f4a768a7644cae/products.html)

Please check the changes and close the ticket if you're happy with them.

**Comment by AbichandaniKaneeka** [comment]
Thank you for adding the tag to the website as instructed. 

I tried testing it using Tag Assistant. Everything looks good for now. 

However, I would like to create a couple of events and check it once. Allow me sometime to do the needful before I close the ticket.

Thanks

**Comment by AbichandaniKaneeka** [comment]
Thanks for making the necessary edits to the tag manager
